[package]
name = "gptcommit"
version = "0.1.4"
edition = "2021"
authors = ["Roger Zurawicki <roger@zura.wiki>"]
description = "A git prepare-commit-msg hook for summarizing commits with GPT-3."
readme = "README.md"
license = "MIT"
repository = "https://github.com/zurawiki/gptcommit"

[[bin]]
name = "gptcommit"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive"] }
colored = "2.0.0"
log = "0.4.17"
reqwest = { version = "0.11.13", features = ["json"] }
serde_json = "1.0.91"
simple_logger = "4.0.0"
tokio = { version = "1.24.1", features = ["full"] }
which = "4.3.0"
